project:
  type: website
  output-dir: ../docs

metadata-files: [CNAME]

website:
  title: "New to Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



